{{- if .Values.secrets.defaultSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-gitlab-tags-exporter.fullname" . }}
  labels:
{{- include "go-gitlab-tags-exporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}